[package]
name = "low_poly"
version = "0.3.0"
authors = ["Bjorn Martens <bjorn@expeditious.nl>"]
edition = "2018"

[dependencies]
bevy = { git = 'https://github.com/bevyengine/bevy' }
rapier3d = "0.3"
anyhow = "1.0"
ron = "0.6"
serde = "1.0"
