[package]
name = "low_poly"
version = "0.3.0"
authors = ["Bjorn Martens <bjorn@expeditious.nl>"]
edition = "2018"

[dependencies]
bevy = "0.4"
rapier3d = "0.4"
anyhow = "1.0"
ron = "0.6"
serde = "1.0"
noise = "0.7"
rand = "0.8"
