[package]
name = "low_poly"
version = "0.3.0"
authors = ["Bjorn Martens <bjorn@expeditious.nl>"]
edition = "2018"

[dependencies]
bevy = { git = 'https://github.com/bevyengine/bevy' }
rapier3d = "0.3.2"
